"""The migration assessment as .xlsx and .pdf, in the shape AWS SCT reports it.

Two documents a client expects from an AWS migration are the SCT conversion
assessment and the DMS pre-migration assessment. They already exist here as
HTML; this renders the same record as the two file formats people actually
circulate -- a spreadsheet they can filter and a PDF they can attach.

**What the numbers are, said plainly.** These come from DBShift's own 50-rule
engine, not from running AWS SCT. The *shape* is SCT's -- action items graded by
the complexity of the work a person must do, the same four buckets, the same
"what converts automatically" headline -- because that is the shape a client
knows how to read. Every document says so on its first page and its first sheet.
Claiming otherwise would be the easiest lie in this project to tell and the
worst one to be caught in.

Nothing here computes. `report/build.py` produces the record; this formats it.
If a number looks wrong, it is wrong upstream.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone

# The line that appears on every artefact this module produces. One constant, so
# it cannot say one thing in the PDF and another in the spreadsheet.
PROVENANCE = (
    "Produced by DBShift from its own 50-rule assessment engine. "
    "Presented in the shape of an AWS SCT assessment; not generated by AWS SCT."
)

COMPLEXITY_ORDER = ["simple", "medium", "complex", "decision"]

# SCT grades by the work a person must do, not by how bad the finding is. Kept
# next to the exports because it is the first thing a client asks about.
COMPLEXITY_MEANING = {
    "simple": "automatic, or a one-line change",
    "medium": "a person edits and reviews it",
    "complex": "a person rewrites it",
    "decision": "not a code change -- someone must decide",
}

_SEV_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}


def _fmt_ts(iso: str | None) -> str:
    if not iso:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M UTC")
    except ValueError:
        return str(iso)


def _summary_rows(rec: dict) -> list[tuple[str, str]]:
    """The headline numbers, as label/value pairs both formats reuse."""
    sc = rec.get("schema_conversion") or {}
    cs = sc.get("code_summary") or {}
    by = sc.get("by_complexity") or {}
    dms = (rec.get("dms_assessment") or {}).get("totals") or {}
    scores = rec.get("scores") or {}

    rows = [
        ("Estate", str(rec.get("estate") or "-")),
        ("Target engine", str(rec.get("target_engine") or "-")),
        ("Collector run", str(rec.get("collector_run_id") or "-")),
        ("Generated", _fmt_ts(rec.get("generated_at_utc"))),
        ("", ""),
        ("Stored code objects", str(cs.get("total", 0))),
        ("Converted automatically", f"{cs.get('automatic', 0)} of {cs.get('convertible', 0)}"
                                    f" ({cs.get('pct_automatic', 0)}%)"),
        ("Needs the model tier", str(cs.get("needs_model", 0))),
        ("Needs a person", str(cs.get("manual", 0))),
        ("", ""),
        ("Action items", str(sum(by.values()) if by else 0)),
    ]
    for c in COMPLEXITY_ORDER:
        rows.append((f"  {c.capitalize()} — {COMPLEXITY_MEANING[c]}", str(by.get(c, 0))))
    if dms:
        rows += [("", ""), ("DMS checks", ", ".join(f"{v} {k}" for k, v in sorted(dms.items())))]
    if scores:
        rows += [("", ""),
                 ("Assessment score", str(scores.get("overall_score", "-"))),
                 ("Critical findings", str(scores.get("critical_findings", 0)))]
    return rows


def _finding_rows(assessment: dict | None) -> list[list]:
    """Findings from Phase 2's record, newest key names, severity-ordered.

    A not-applicable finding keeps its reason and its original severity and is
    never dropped -- a spreadsheet that silently omitted them would read as
    "clean", which is the one claim Phase 1 forbids.
    """
    findings = (assessment or {}).get("findings") or []
    rows = [[
        f.get("rule_id", ""), f.get("severity", ""),
        "no" if f.get("applies") is False else "yes",
        f.get("severity_if_applicable", "") or "",
        f.get("not_applicable_because", "") or "",
        f.get("category", ""), f.get("title", ""), f.get("owner", ""),
        f.get("object_name", ""), f.get("remediation_level", ""), f.get("detail", ""),
    ] for f in findings]
    rows.sort(key=lambda r: (_SEV_ORDER.get(r[1], 9), r[0], r[8]))
    return rows


# --------------------------------------------------------------------- Excel


def workbook(rec: dict, assessment: dict | None = None) -> bytes:
    """The assessment as .xlsx. Four sheets, because a client filters them.

    Sheet order is the order the questions get asked: what is the headline, what
    must someone do, what did we find, what happens to the stored code.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    head_font = Font(bold=True, color="FFFFFF")
    head_fill = PatternFill("solid", fgColor="1F4E5F")
    title_font = Font(bold=True, size=13)
    wrap = Alignment(vertical="top", wrap_text=True)

    def sheet(ws, title, columns, rows, widths):
        ws.cell(row=1, column=1, value=title).font = title_font
        ws.cell(row=2, column=1, value=PROVENANCE).font = Font(italic=True, size=9)
        for i, c in enumerate(columns, 1):
            cell = ws.cell(row=4, column=i, value=c)
            cell.font, cell.fill = head_font, head_fill
        for r, row in enumerate(rows, 5):
            for i, v in enumerate(row, 1):
                ws.cell(row=r, column=i, value=v).alignment = wrap
        for i, w in enumerate(widths, 1):
            ws.column_dimensions[get_column_letter(i)].width = w
        # Freeze under the header so a long list keeps its column names.
        ws.freeze_panes = "A5"
        if rows:
            ws.auto_filter.ref = f"A4:{get_column_letter(len(columns))}{4 + len(rows)}"

    # 1. Summary
    ws = wb.active
    ws.title = "Summary"
    sheet(ws, "Migration assessment — summary", ["Measure", "Value"],
          _summary_rows(rec), [46, 52])

    # 2. Action items -- the sheet a client actually works from
    sc = rec.get("schema_conversion") or {}
    items = sc.get("action_items") or []
    rows = [[
        i.get("complexity", ""), COMPLEXITY_MEANING.get(i.get("complexity", ""), ""),
        i.get("severity", ""), i.get("rule_id", ""), i.get("title", ""),
        i.get("occurrences", 0),
        ", ".join(i.get("objects") or []) + (f" (+{i['more']} more)" if i.get("more") else ""),
        i.get("recommendation", ""),
    ] for i in sorted(items, key=lambda x: (
        COMPLEXITY_ORDER.index(x["complexity"]) if x.get("complexity") in COMPLEXITY_ORDER else 9,
        -(x.get("occurrences") or 0)))]
    sheet(wb.create_sheet("Action items"), "What a person must do",
          ["Complexity", "Meaning", "Severity", "Rule", "Finding", "Objects", "Where", "Recommendation"],
          rows, [12, 28, 10, 10, 40, 9, 40, 64])

    # 3. Findings -- one row per finding, for pivoting.
    #
    # They live in Phase 2's record, not the report record, which carries only
    # the rolled-up counts. Passing the assessment is therefore how this sheet
    # gets populated; without it the sheet says so rather than appearing empty
    # and looking like a clean estate.
    frows = _finding_rows(assessment)
    ws3 = wb.create_sheet("Findings")
    sheet(ws3, "Every finding" if frows else "Every finding — not available",
          ["Rule", "Severity", "Applies", "Severity if applicable", "Why not applicable",
           "Category", "Finding", "Schema", "Object", "Remediation", "Detail"],
          frows, [10, 10, 9, 18, 34, 18, 40, 16, 24, 12, 52])
    if not frows:
        # An empty sheet reads as "nothing was found". Say which it is.
        ws3.cell(row=5, column=1,
                 value="No assessment record was supplied to this export, so the "
                       "per-finding detail is not included. This is not a statement "
                       "that the estate is clean — see the Summary sheet for the counts.")

    # 4. Stored code. `code_objects` is a rollup BY TYPE -- one row per object
    # type with counts, not one row per object. Labelled as what it is rather
    # than given object-name columns it cannot fill.
    crows = [[c.get("type", ""), c.get("total", 0), c.get("automatic", 0),
              c.get("model_converted", 0), c.get("needs_model", 0), c.get("manual", 0),
              c.get("excluded", 0), c.get("rejected", 0)]
             for c in (sc.get("code_objects") or [])]
    sheet(wb.create_sheet("Stored code"), "PL/SQL conversion, by object type",
          ["Type", "Total", "Automatic", "Model", "Needs model", "Needs a person",
           "Excluded", "Rejected"], crows, [18, 10, 12, 10, 14, 16, 12, 11])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ----------------------------------------------------------------------- PDF


def pdf(rec: dict, assessment: dict | None = None) -> bytes:
    """The assessment as .pdf -- the document that gets attached to an email.

    Deliberately not a print of the HTML report: a PDF is read linearly and
    cannot be expanded, so the action items are a paginated table with the
    complexity meaning spelled out rather than an accordion that must be clicked.
    """
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (KeepTogether, PageBreak, Paragraph,
                                    SimpleDocTemplate, Spacer, Table, TableStyle)

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=17, spaceAfter=4,
                        textColor=colors.HexColor("#14343f"))
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=12, spaceBefore=12,
                        spaceAfter=5, textColor=colors.HexColor("#1f4e5f"))
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=9, leading=12.5)
    small = ParagraphStyle("small", parent=body, fontSize=7.8, leading=10.5,
                           textColor=colors.HexColor("#5b6b70"))
    cell = ParagraphStyle("cell", parent=body, fontSize=7.6, leading=9.8, alignment=TA_LEFT)

    buf = io.BytesIO()
    estate = rec.get("estate") or "estate"
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        leftMargin=14 * mm, rightMargin=14 * mm, topMargin=13 * mm, bottomMargin=14 * mm,
        title=f"DBShift migration assessment — {estate}", author="DBShift")

    def footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.2)
        canvas.setFillColor(colors.HexColor("#77878c"))
        canvas.drawString(14 * mm, 8 * mm, PROVENANCE)
        canvas.drawRightString(landscape(A4)[0] - 14 * mm, 8 * mm, f"page {canvas.getPageNumber()}")
        canvas.restoreState()

    def grid(data, widths, header=True):
        t = Table(data, colWidths=widths, repeatRows=1 if header else 0)
        style = [
            ("FONTSIZE", (0, 0), (-1, -1), 7.6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d5dee0")),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, colors.HexColor("#f5f8f9")]),
        ]
        if header:
            style += [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f4e5f")),
                      ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                      ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")]
        t.setStyle(TableStyle(style))
        return t

    story = [
        Paragraph(f"Migration assessment — {estate}", h1),
        Paragraph(
            f"Target: <b>{rec.get('target_engine') or '-'}</b> &nbsp;·&nbsp; "
            f"Collector run: {rec.get('collector_run_id') or '-'} &nbsp;·&nbsp; "
            f"Generated {_fmt_ts(rec.get('generated_at_utc'))}", small),
        Spacer(1, 7),
        Paragraph(PROVENANCE, small),
        Spacer(1, 4),
    ]

    # Summary
    story += [Paragraph("Summary", h2)]
    srows = [[Paragraph(f"<b>{k}</b>" if k and not k.startswith("  ") else k, cell),
              Paragraph(v, cell)] for k, v in _summary_rows(rec) if k or v]
    story += [grid([[Paragraph("<b>Measure</b>", cell), Paragraph("<b>Value</b>", cell)]] + srows,
                   [110 * mm, 145 * mm])]

    # Action items
    sc = rec.get("schema_conversion") or {}
    items = sorted(sc.get("action_items") or [], key=lambda x: (
        COMPLEXITY_ORDER.index(x["complexity"]) if x.get("complexity") in COMPLEXITY_ORDER else 9,
        -(x.get("occurrences") or 0)))
    story += [PageBreak(), Paragraph("Action items", h2),
              Paragraph("Graded by the work a person must do, which is how SCT grades them — "
                        "not by how severe the finding is.", small), Spacer(1, 5)]
    if items:
        rows = [[Paragraph(f"<b>{c}</b>", cell) for c in
                 ("Complexity", "Severity", "Rule", "Finding", "N", "Where", "Recommendation")]]
        for i in items:
            where = ", ".join((i.get("objects") or [])[:6])
            if i.get("more"):
                where += f" (+{i['more']} more)"
            rows.append([
                Paragraph(i.get("complexity", ""), cell),
                Paragraph(i.get("severity", ""), cell),
                Paragraph(i.get("rule_id", ""), cell),
                Paragraph(i.get("title", ""), cell),
                Paragraph(str(i.get("occurrences", "")), cell),
                Paragraph(where, cell),
                Paragraph(i.get("recommendation", ""), cell),
            ])
        story += [grid(rows, [20 * mm, 17 * mm, 16 * mm, 52 * mm, 8 * mm, 54 * mm, 88 * mm])]
    else:
        story += [Paragraph("No action items.", body)]

    # DMS assessment
    dms = rec.get("dms_assessment") or {}
    checks = dms.get("checks") or []
    if checks:
        story += [PageBreak(), Paragraph("DMS pre-migration assessment", h2)]
        rows = [[Paragraph(f"<b>{c}</b>", cell) for c in ("Status", "Check", "Detail")]]
        order = {"fail": 0, "warning": 1, "pass": 2, "info": 3}
        for c in sorted(checks, key=lambda x: order.get(x.get("status", ""), 9)):
            rows.append([Paragraph(str(c.get("status", "")), cell),
                         Paragraph(str(c.get("name", c.get("check", ""))), cell),
                         Paragraph(str(c.get("detail", "")), cell)])
        story += [grid(rows, [20 * mm, 60 * mm, 175 * mm])]

    # Findings, when Phase 2's record was supplied. Last on purpose: a reader
    # wants the headline and the work first; this is the appendix they turn to
    # when they want to check a specific object.
    frows = _finding_rows(assessment)
    if frows:
        story += [PageBreak(), Paragraph("Findings", h2),
                  Paragraph(f"{len(frows)} findings, most severe first. A finding marked "
                            "<b>Applies: no</b> is not a blocker for the migration that was "
                            "declared, and keeps the severity it would otherwise carry.", small),
                  Spacer(1, 5)]
        rows = [[Paragraph(f"<b>{c}</b>", cell) for c in
                 ("Rule", "Severity", "Applies", "Finding", "Schema", "Object", "Detail")]]
        for r in frows:
            rows.append([Paragraph(str(r[0]), cell), Paragraph(str(r[1]), cell),
                         Paragraph(str(r[2]), cell), Paragraph(str(r[6]), cell),
                         Paragraph(str(r[7]), cell), Paragraph(str(r[8]), cell),
                         Paragraph(str(r[10])[:300], cell)])
        story += [grid(rows, [16 * mm, 18 * mm, 13 * mm, 58 * mm, 26 * mm, 40 * mm, 84 * mm])]

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buf.getvalue()


def filename(rec: dict, ext: str) -> str:
    estate = str(rec.get("estate") or "estate").lower().replace(" ", "-")
    run = str(rec.get("collector_run_id") or "run")[:8]
    return f"dbshift-assessment-{estate}-{run}.{ext}"
