"""Offline checks for the .xlsx and .pdf exports. No database, no AWS.

Two things are being checked, and the second matters more than the first.

  1. The files are real files -- a valid workbook with the sheets it claims, a
     PDF with pages -- and they carry the record's actual numbers rather than
     placeholders.

  2. **They never claim to be AWS SCT output.** The shape is SCT's and the data
     is ours, and every artefact has to say so. That is the easiest lie in this
     project to tell by accident: drop the provenance line while tidying a
     header and the spreadsheet silently becomes a forgery a client would
     circulate. So the provenance is asserted in the PDF text, on every sheet,
     and in the constant itself.
"""

from __future__ import annotations

import io
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    __package__ = "report"

from . import export as E

PASS = FAIL = 0


def check(label, got, want):
    global PASS, FAIL
    if got == want:
        PASS += 1
        print(f"  [ok] {label}")
    else:
        FAIL += 1
        print(f"  [XX] {label}\n       got  {got!r}\n       want {want!r}")


def record() -> dict:
    return {
        "generated_at_utc": "2026-09-17T03:39:00+00:00",
        "collector_run_id": "053912d0-257e-4fb0-9748-cf3938b5ded6",
        "estate": "DBMIG_APP",
        "target_engine": "POSTGRESQL",
        "scores": {"overall_score": 49, "critical_findings": 4},
        "schema_conversion": {
            "code_summary": {"total": 8, "automatic": 6, "convertible": 7,
                             "pct_automatic": 86, "needs_model": 0, "manual": 0},
            "by_complexity": {"simple": 2, "medium": 17, "complex": 17, "decision": 2},
            "code_objects": [
                {"type": "FUNCTION", "total": 2, "automatic": 2, "model_converted": 0,
                 "needs_model": 0, "manual": 0, "excluded": 0, "rejected": 0},
                {"type": "PACKAGE", "total": 1, "automatic": 1, "model_converted": 0,
                 "needs_model": 0, "manual": 0, "excluded": 0, "rejected": 0},
            ],
            "action_items": [
                {"complexity": "simple", "level": "L1", "severity": "MEDIUM",
                 "rule_id": "DQ-007", "title": "Optimizer statistics are stale",
                 "occurrences": 1, "objects": ["PAYMENT_HIST"], "more": 0,
                 "recommendation": "Gather statistics before sizing reads them."},
                {"complexity": "complex", "level": "L3", "severity": "CRITICAL",
                 "rule_id": "RDS-004", "title": "External table cannot be migrated as-is",
                 "occurrences": 1, "objects": ["EXT_CUSTOMER_EXTRACT"], "more": 3,
                 "recommendation": "Re-point at S3 integration on the target."},
            ],
        },
        "dms_assessment": {
            "totals": {"pass": 1, "warning": 5, "fail": 1},
            "checks": [
                {"name": "primary keys", "status": "fail", "detail": "2 tables have none"},
                {"name": "supplemental logging", "status": "warning", "detail": "not enabled"},
            ],
        },
    }


def assessment() -> dict:
    return {"findings": [
        {"rule_id": "RDS-004", "severity": "CRITICAL", "category": "rds_compatibility",
         "title": "External table", "owner": "DBMIG_APP", "object_name": "EXT_CUSTOMER_EXTRACT",
         "remediation_level": "L3", "detail": "directory-based", "applies": True},
        {"rule_id": "OPS-001", "severity": "INFO", "category": "operational_risk",
         "title": "NOARCHIVELOG", "owner": "DBMIG_APP", "object_name": "XE",
         "remediation_level": "L3", "detail": "log_mode", "applies": False,
         "severity_if_applicable": "CRITICAL",
         "not_applicable_because": "CDC is not in scope for a full-load migration"},
        {"rule_id": "DQ-007", "severity": "MEDIUM", "category": "data_quality",
         "title": "Stale statistics", "owner": "DBMIG_APP", "object_name": "PAYMENT_HIST",
         "remediation_level": "L1", "detail": "last analyzed 2026-09-08", "applies": True},
    ]}


def main() -> int:
    rec, asm = record(), assessment()

    print("the provenance line -- the check that matters most")
    check("it names DBShift as the source", "DBShift" in E.PROVENANCE, True)
    check("it says it is NOT AWS SCT output",
          "not generated by AWS SCT" in E.PROVENANCE, True)

    print("\nthe workbook")
    from openpyxl import load_workbook
    wb = load_workbook(io.BytesIO(E.workbook(rec, asm)))
    check("four sheets, in the order the questions get asked",
          wb.sheetnames, ["Summary", "Action items", "Findings", "Stored code"])
    for name in wb.sheetnames:
        ws = wb[name]
        check(f"{name}: carries the provenance line",
              E.PROVENANCE in str(ws.cell(row=2, column=1).value or ""), True)
        check(f"{name}: header row is frozen", ws.freeze_panes, "A5")
    check("action items: one row per item", wb["Action items"].max_row - 4, 2)
    check("findings: one row per finding", wb["Findings"].max_row - 4, 3)
    check("stored code: one row per type", wb["Stored code"].max_row - 4, 2)
    check("every sheet is filterable",
          all(wb[n].auto_filter.ref for n in wb.sheetnames), True)

    ws = wb["Summary"]
    vals = {str(ws.cell(row=r, column=1).value): str(ws.cell(row=r, column=2).value)
            for r in range(5, ws.max_row + 1)}
    check("the summary carries the real conversion figure",
          vals.get("Converted automatically"), "6 of 7 (86%)")
    check("and the estate", vals.get("Estate"), "DBMIG_APP")

    # A not-applicable finding must survive into the spreadsheet with its reason.
    ws = wb["Findings"]
    rows = [[ws.cell(row=r, column=c).value for c in range(1, 12)]
            for r in range(5, ws.max_row + 1)]
    na = next((r for r in rows if r[0] == "OPS-001"), None)
    check("a not-applicable finding is exported, not dropped", na is not None, True)
    check("it says it does not apply", na[2], "no")
    check("it keeps the severity it would otherwise carry", na[3], "CRITICAL")
    check("and the reason", "CDC" in (na[4] or ""), True)
    check("findings are severity-ordered, worst first", rows[0][1], "CRITICAL")

    print("\nthe workbook without an assessment")
    wb2 = load_workbook(io.BytesIO(E.workbook(rec)))
    ws2 = wb2["Findings"]
    check("the sheet still exists", "Findings" in wb2.sheetnames, True)
    check("and says the detail is missing rather than looking clean",
          "not a statement" in str(ws2.cell(row=5, column=1).value or ""), True)

    print("\nthe PDF")
    data = E.pdf(rec, asm)
    check("it is a PDF", data[:5], b"%PDF-")
    from pypdf import PdfReader
    r = PdfReader(io.BytesIO(data))
    check("it has pages", len(r.pages) >= 2, True)
    text = "\n".join(p.extract_text() or "" for p in r.pages)
    for probe, label in [
        ("not generated by AWS SCT", "the provenance line is in the document"),
        ("DBMIG_APP", "the estate"),
        ("POSTGRESQL", "the target engine"),
        ("Action items", "the action items section"),
        ("Optimizer statistics", "an actual action item"),
        ("DMS pre-migration", "the DMS section"),
        ("Findings", "the findings section"),
        ("OPS-001", "a not-applicable finding is still listed"),
    ]:
        check(label, probe in text, True)
    check("the complexity grading is explained, not just labelled",
          "work a person must do" in text, True)

    print("\nthe PDF without an assessment")
    text2 = "\n".join(p.extract_text() or ""
                      for p in PdfReader(io.BytesIO(E.pdf(rec))).pages)
    check("it still renders", "Action items" in text2, True)
    check("and omits the findings appendix rather than faking one",
          "OPS-001" in text2, False)

    print("\nfilenames")
    check("the workbook is named for the estate and run",
          E.filename(rec, "xlsx"), "dbshift-assessment-dbmig_app-053912d0.xlsx")
    check("and the PDF likewise",
          E.filename(rec, "pdf"), "dbshift-assessment-dbmig_app-053912d0.pdf")
    check("a record with nothing in it still yields a filename",
          E.filename({}, "pdf"), "dbshift-assessment-estate-run.pdf")

    print("\nempty records do not crash")
    check("an empty workbook builds", len(E.workbook({})) > 0, True)
    check("an empty PDF builds", E.pdf({})[:5], b"%PDF-")

    print(f"\n{PASS}/{PASS + FAIL} checks passed")
    return 1 if FAIL else 0


if __name__ == "__main__":
    raise SystemExit(main())
