"""SCT's own CSV as an .xlsx workbook, with its data untouched.

SCT writes PDF and CSV. A client asks for "PDF and Excel", so the CSV needs a
workbook around it -- and that is *all* this module does.

**The contrast with `report/export.py` is the whole point.** That module renders
DBShift's own 50-rule findings into SCT's *shape*, and carries a provenance line
on every page and sheet saying it is **not** generated by AWS SCT. This module
handles the real thing: every value here came out of AWS SCT, and the only thing
added is the container. So the provenance says the opposite, and a `Provenance`
sheet records the tool, the version, the target and the run that produced it.

Nothing is recomputed, reordered or re-graded. If a number looks wrong it is
SCT's number, which is the property that makes this document worth having.
"""

from __future__ import annotations

import csv
import io
from datetime import datetime, timezone
from pathlib import Path

# The claim this module makes, as one constant so it cannot say one thing on the
# data sheet and another on the provenance sheet. The inverse of
# `report.export.PROVENANCE`, deliberately.
PROVENANCE = (
    "Generated by AWS Schema Conversion Tool. The rows on the 'SCT assessment' "
    "sheet are SCT's own output, unmodified; only the workbook container was added."
)

MAX_COL_WIDTH = 70

# Characters that must not reach a `Content-Disposition` filename. RFC 6266
# allows a quoted string, but browsers are inconsistent with spaces, parentheses
# and separators inside one -- and when a browser rejects the parse it falls back
# to naming the file after the URL or a GUID, with **no extension**, which then
# will not open.
#
# This is not hypothetical here: SCT names its CSV after the *virtual target*,
# so the real filename is `PostgreSQL_3cPostgreSQL (virtual)3e.csv` -- a space
# and two parentheses, straight from the vendor. `report/export.py` has always
# sanitised (`.replace(" ", "-")`); this path passed SCT's names through raw and
# downloads arrived as GUIDs in interactive Edge.
_FILENAME_SAFE = set(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_."
)


def safe_filename(name: str, fallback: str = "aws-sct-report") -> str:
    """An ASCII filename a browser will accept in a Content-Disposition header.

    Collapses every unsafe character to a hyphen, keeps the extension, and never
    returns an empty stem -- a name of nothing but unsafe characters would
    otherwise produce a bare ".pdf".
    """
    from pathlib import Path as _P

    p = _P(str(name or ""))
    ext = p.suffix.lower()
    stem = p.stem

    cleaned = "".join(c if c in _FILENAME_SAFE else "-" for c in stem)
    # Collapse runs of hyphens and trim them from the ends.
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    cleaned = cleaned.strip("-.")

    if not cleaned:
        cleaned = fallback
    # Windows caps a path component at 255; leave room for a prefix.
    return (cleaned[:180] + ext) if ext else cleaned[:180]


def _fmt_ts(iso: str | None) -> str:
    if not iso:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    try:
        return datetime.fromisoformat(str(iso).replace("Z", "+00:00")).strftime(
            "%Y-%m-%d %H:%M UTC")
    except ValueError:
        return str(iso)


def _sct_version(record: dict) -> str:
    """SCT's version, from the batch jar's path if the record does not carry it."""
    jar = ((record.get("toolchain") or {}).get("sct_batch_jar")) or ""
    # An admin-extracted install has no registry entry, so the version is not
    # discoverable from Windows -- report the path and let the PDF, which SCT
    # stamps itself, be the authority.
    return jar or "unknown"


def _provenance_rows(record: dict, csv_path: Path) -> list[tuple[str, str]]:
    target = record.get("target") or {}
    source = record.get("source") or {}
    host = record.get("host") or {}
    rows = [
        ("Produced by", "AWS Schema Conversion Tool"),
        ("SCT batch jar", _sct_version(record)),
        ("Java runtime", str((record.get("toolchain") or {}).get("java") or "-")),
        ("", ""),
        ("Target platform", f"{target.get('label', '-')} ({target.get('sct_platform', '-')})"),
        ("In DBShift migration scope", "yes" if target.get("in_scope") else "no"),
    ]
    if not target.get("in_scope"):
        # An out-of-scope target is assessed for comparison only, and the
        # workbook must say so -- a client circulating this should not read it
        # as a migration plan.
        rows.append(("Scope note", str(target.get("scope_note") or "")))
    rows += [
        ("", ""),
        ("Source", str(source.get("dsn") or "-")),
        ("Source account", str(source.get("user") or "-")),
        ("Schemas assessed", ", ".join(source.get("schemas") or []) or "-"),
        ("Collector run", str(record.get("collector_run_id") or "-")),
        ("", ""),
        ("Assessed", _fmt_ts(record.get("assessed_at_utc"))),
        ("Finished", _fmt_ts(record.get("finished_at_utc"))),
        ("Ran on", str(host.get("host") or "-")),
        ("SCT source file", csv_path.name),
        ("", ""),
        ("Provenance", PROVENANCE),
    ]
    return rows


def workbook_from_sct_csv(csv_path: str | Path, record: dict | None = None) -> bytes:
    """SCT's CSV as a two-sheet workbook: its rows, and where they came from.

    The data sheet is a faithful copy -- same columns, same order, same values,
    including any column this project's parser does not understand. Filtering
    and freezing the header are presentation only; a client works this sheet
    rather than reading it.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    csv_path = Path(csv_path)
    record = record or {}

    # utf-8-sig: SCT may write a BOM, and it must not become part of the first
    # header cell.
    with csv_path.open("r", encoding="utf-8-sig", errors="replace", newline="") as fh:
        rows = list(csv.reader(fh))

    wb = Workbook()

    head_font = Font(bold=True, color="FFFFFF")
    head_fill = PatternFill("solid", fgColor="232F3E")   # AWS squid ink
    label_font = Font(bold=True)

    # ---- Sheet 1: SCT's rows, verbatim -------------------------------------
    ws = wb.active
    ws.title = "SCT assessment"

    if rows:
        widths: dict[int, int] = {}
        for r, row in enumerate(rows, start=1):
            for c, value in enumerate(row, start=1):
                cell = ws.cell(row=r, column=c, value=value)
                if r == 1:
                    cell.font = head_font
                    cell.fill = head_fill
                    cell.alignment = Alignment(vertical="center", wrap_text=True)
                widths[c] = min(max(widths.get(c, 10), len(str(value)) + 2), MAX_COL_WIDTH)
        for c, w in widths.items():
            ws.column_dimensions[get_column_letter(c)].width = w
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = (
            f"A1:{get_column_letter(max(len(r) for r in rows))}{len(rows)}"
        )
        ws.row_dimensions[1].height = 30
    else:
        # An empty CSV must read as "SCT reported nothing here", never as a
        # clean estate. Phase 1 forbids that confusion, and an empty sheet
        # invites it.
        ws["A1"] = "AWS SCT produced no rows in its assessment CSV."
        ws["A1"].font = label_font
        ws["A2"] = ("This is not the same as an estate with no findings. Check the "
                    "provenance sheet and SCT's own log before drawing a conclusion.")
        ws.column_dimensions["A"].width = 100

    # ---- Sheet 2: provenance ----------------------------------------------
    ps = wb.create_sheet("Provenance")
    ps["A1"] = "Where these numbers come from"
    ps["A1"].font = Font(bold=True, size=13)
    for i, (label, value) in enumerate(_provenance_rows(record, csv_path), start=3):
        ps.cell(row=i, column=1, value=label).font = label_font
        cell = ps.cell(row=i, column=2, value=value)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
    ps.column_dimensions["A"].width = 28
    ps.column_dimensions["B"].width = 96

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
