"""Offline checks for the SCT path. No SCT, no database, no AWS.

What is being checked, in order of how much it matters:

  1. **The password never survives the run.** The scenario file holds it because
     SCT's CLI has no other way to take it; the record must not, the redaction
     must work, and the file must be deleted even when SCT fails.
  2. **Out-of-scope targets stay out of scope.** Aurora and Redshift are listed
     for the dropdown but carry no migration engine, so a selected target cannot
     leak into Phase 3 as a migration path.
  3. **Provenance is inverted from `report/export.py` and must stay that way.**
     That module's whole job is saying "not generated by AWS SCT"; this one's
     output *is* SCT's, and mixing the two claims in either direction is the
     failure mode worth a test.
  4. The parser reads SCT's CSV, sorts it, and reports what it did not
     understand rather than dropping it.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    __package__ = "sct"

from . import parse, route, runner, scenario, targets, toolchain

PASS = FAIL = 0


def check(label, got, want):
    global PASS, FAIL
    if got == want:
        PASS += 1
        print(f"  [ok] {label}")
    else:
        FAIL += 1
        print(f"  [XX] {label}\n       got  {got!r}\n       want {want!r}")


def truthy(label, got):
    check(label, bool(got), True)


# SCT 1.0.677's **real** header and real rows, from the run against DBMIG_APP on
# 2026-09-17. Not invented: the first version of this fixture guessed the column
# names and every guess that mattered was wrong. If SCT's format changes, replace
# this with a fresh capture rather than editing it to pass.
SAMPLE_CSV = (
    '"Category","Occurrence","Action item","Subject","Group","Description",'
    '"Documentation references","Recommended action","Filtered",'
    '"Estimated complexity","Line","Position","Source","Target",'
    '"Server IP address and port","Database name","Schema name"\n'
    '"queuing-table","Schemas.DBMIG_APP.Queuing.Tables.LOAN_EVENT_QTAB","9994",'
    '"Queuing","Unable to convert objects",'
    '"Unable to convert objects of the Queuing category","",'
    '"Perform manual conversion.","","Complex","","","ORACLE",'
    '"<PostgreSQL (virtual)>","localhost:1521","XEPDB1","DBMIG_APP"\n'
    '"table","Schemas.DBMIG_APP.Tables.CUSTOMER.Columns.ADDRESS#","5984","",'
    '"Specify the precision and scale values for your source column",'
    '"Specify the precision and scale values","",'
    '"To improve the conversion, specify the precision.","","Decision","","",'
    '"ORACLE","<PostgreSQL (virtual)>","localhost:1521","XEPDB1","DBMIG_APP"\n'
    '"table","Schemas.DBMIG_APP.Tables.LOAN.Columns.LEGACY_SCORE","5984","",'
    '"Specify the precision and scale values for your source column",'
    '"Specify the precision and scale values","",'
    '"To improve the conversion, specify the precision.","","Decision","","",'
    '"ORACLE","<PostgreSQL (virtual)>","localhost:1521","XEPDB1","DBMIG_APP"\n'
    '"Database link","Schemas.DBMIG_APP.Database Links.DBMIG_LOOPBACK_LNK","5639",'
    '"","Make sure that you installed the postgres_fdw extension",'
    '"Make sure that you installed the postgres_fdw extension","",'
    '"Review your connection options.","","Simple","","","ORACLE",'
    '"<PostgreSQL (virtual)>","localhost:1521","XEPDB1","DBMIG_APP"\n'
)


def test_targets():
    print("targets")
    ids = {t["id"] for t in targets.TARGETS}
    check("four targets offered", len(targets.TARGETS), 4)
    truthy("rds-oracle and rds-postgresql present",
           {"rds-oracle", "rds-postgresql"} <= ids)
    check("in-scope ids", sorted(targets.in_scope_ids()), ["rds-oracle", "rds-postgresql"])

    # The scope rule, tested rather than trusted: an out-of-scope target must
    # carry no engine, because that is what stops Phase 3 accepting it.
    for t in targets.TARGETS:
        if not t["in_scope"]:
            check(f"{t['id']} has no migration engine", t["engine"], None)
            truthy(f"{t['id']} explains why", len(t["scope_note"]) > 20)
        else:
            truthy(f"{t['id']} has an engine", t["engine"])

    console = targets.for_console()
    check("in-scope sorted first", [t["in_scope"] for t in console],
          [True, True, False, False])
    check("exactly one default", sum(1 for t in console if t["default"]), 1)
    truthy("aurora is listed, not hidden", any(t["id"] == "aurora-postgresql" for t in console))
    truthy("redshift is listed, not hidden", any(t["id"] == "redshift" for t in console))

    try:
        targets.get("mysql")
        check("unknown target refused", "no error", "UnknownTarget")
    except targets.UnknownTarget as exc:
        truthy("unknown target names the valid ids", "rds-postgresql" in str(exc))


def test_scenario():
    print("scenario")
    s = scenario.build_script(
        project_name="p", project_dir=Path("C:/tmp/p"), report_dir=Path("C:/tmp/r"),
        log_dir=Path("C:/tmp/l"), target_id="rds-postgresql", dsn="localhost:1521/XEPDB1",
        user="dbmig_collector", password="SUPERSECRET", schemas=["DBMIG_APP", "DBMIG_RPT"],
        jdbc_jar=Path("C:/x/ojdbc8.jar"),
    )

    # The format is SCT's own language, not JSON. A JSON file is rejected with
    # AntlrParsingException at line 1:0 -- which is how v1 was caught.
    check("not JSON", s.lstrip().startswith("{"), False)
    truthy("commands terminated by a bare slash", "\n/\n" in s)
    truthy("values in straight single quotes", "-save: 'false'" in s)

    cmds = scenario.command_names(s)
    check("commands in SCT's documented order", cmds, [
        "SetGlobalSettings", "SetGlobalSettings", "CreateProject", "CreateFilter",
        "AddSource", "AddServerMapping", "CreateReport", "SaveReportPDF",
        "SaveReportCSV", "SaveProject",
    ])
    truthy("inline JSON braces are not parsed as commands",
           not any(c in ("}", "]") for c in cmds))

    # The JDBC driver must be registered or AddSource fails on the driver
    # rather than the connection.
    truthy("driver registered via SetGlobalSettings", "oracle_driver_file" in s)
    truthy("driver path JSON-escaped once", "ojdbc8.jar" in s)
    check("driver path not double-escaped", "\\" * 4 in s, False)

    # Oracle XEPDB1 is a pluggable database: reached by service name, not SID.
    truthy("service-name connection type", "BASIC_SERVICE_NAME" in s)
    truthy("host split out", "-host: 'localhost'" in s)
    truthy("port split out", "-port: '1521'" in s)
    truthy("service split out", "-serviceName: 'XEPDB1'" in s)

    # The virtual target is what the dropdown changes.
    truthy("maps onto the virtual PostgreSQL target",
           "Servers.<PostgreSQL (virtual)>" in s)
    for t in targets.TARGETS:
        truthy(f"{t['id']} has a virtual target", t.get("sct_virtual_target"))

    # PDF takes a file, CSV takes a directory. Not symmetrical.
    truthy("PDF saved to a file path", "SaveReportPDF\n    -file:" in s)
    truthy("CSV saved to a directory", "SaveReportCSV\n    -directory:" in s)

    # Scope: without a filter SCT reports the whole instance.
    truthy("schemas scoped by filter", "DBMIG_APP" in s and "DBMIG_RPT" in s)

    # The one that matters.
    red = scenario.redacted(s)
    check("password redacted out of the record", "SUPERSECRET" in red, False)
    truthy("redaction masks the parameter", "-password: '***'" in red)
    truthy("unredacted script still carries it for SCT", "SUPERSECRET" in s)

    # A value containing a single quote would end the string early; SCT has no
    # escape for it, so it must be refused rather than silently mis-parsed.
    try:
        scenario.build_script(
            project_name="p", project_dir=Path("."), report_dir=Path("."),
            log_dir=Path("."), target_id="rds-postgresql", dsn="localhost:1521/XEPDB1",
            user="u", password="pa'ss", schemas=["S"], jdbc_jar=Path("j"),
        )
        check("quote in a value refused", "accepted", "ValueError")
    except ValueError:
        check("quote in a value refused with a reason", True, True)

    for bad in ("localhost:1521", "localhost/XEPDB1", "localhost:abc/XEPDB1"):
        try:
            scenario.build_script(
                project_name="p", project_dir=Path("."), report_dir=Path("."),
                log_dir=Path("."), target_id="rds-postgresql", dsn=bad, user="u",
                password="p", schemas=["S"], jdbc_jar=Path("j"),
            )
            check(f"dsn {bad!r} refused", "accepted", "ValueError")
        except ValueError:
            check(f"dsn {bad!r} refused with a reason", True, True)

    try:
        scenario.build_script(
            project_name="p", project_dir=Path("."), report_dir=Path("."),
            log_dir=Path("."), target_id="rds-postgresql", dsn="localhost:1521/XEPDB1",
            user="u", password="p", schemas=[], jdbc_jar=Path("j"),
        )
        check("empty schema list refused", "accepted", "ValueError")
    except ValueError:
        check("empty schema list refused with a reason", True, True)


def test_parser():
    print("parser")
    r = parse.parse_csv_text(SAMPLE_CSV)

    # SCT emits one row per OCCURRENCE, not one per issue with a count. Four
    # rows, two of which share an action item, must group to three items and
    # four occurrences. Reading `Occurrence` as a number -- which the first
    # version did -- gave 0 for every row.
    check("rows grouped into action items", r["action_item_count"], 3)
    check("every occurrence counted", r["occurrence_count"], 4)
    check("bucketed by complexity", r["by_complexity"],
          {"simple": 1, "medium": 0, "complex": 1, "decision": 1})
    check("occurrences bucketed", r["occurrences_by_complexity"],
          {"simple": 1, "medium": 0, "complex": 1, "decision": 2})

    # **Every column of SCT's real 17 must be accounted for.** This is the
    # assertion that would have caught the original guesswork: the first
    # version reported 9 of them as not understood.
    check("no column left unmapped", r["unmapped_columns"], [])

    by_code = {i["issue_code"]: i for i in r["issues"]}
    check("action-item codes read", sorted(by_code), ["5639", "5984", "9994"])

    # `Action item` is the CODE, not a title; `Group` is the readable statement.
    it = by_code["5984"]
    check("the title is the readable problem statement",
          it["title"], "Specify the precision and scale values for your source column")
    check("two rows of one code grouped", it["occurrences"], 2)
    # **Objects are qualified with their parent.** A column occurrence's leaf
    # is a bare column name -- ADDRESS#, STATUS -- useless on its own: the
    # console showed column names with no table and nobody could act on them.
    truthy("a grouped item lists its objects, table-qualified",
           set(it["objects"]) == {"CUSTOMER.ADDRESS#", "LOAN.LEGACY_SCORE"})
    check("a grouped item says how many objects", it["object_name"], "2 objects")

    # Oracle's own internals are counted apart from the client's objects.
    truthy("DR$ is recognised as internal", parse.is_internal_object("DR$IX_FOO$I"))
    truthy("AQ$ is recognised as internal", parse.is_internal_object("AQ$_Q_H"))
    check("a user table is not internal", parse.is_internal_object("CUSTOMER"), False)
    check("an empty name is not internal", parse.is_internal_object(""), False)

    mixed_csv = "\n".join([
        '"Category","Occurrence","Action item","Group","Estimated complexity","Schema name"',
        '"table","Schemas.DBMIG_APP.Tables.DR$IX_NOTES$B.Columns.STATUS","5984","Specify the precision","Decision","DBMIG_APP"',
        '"table","Schemas.DBMIG_APP.Tables.AQ$_Q_H.Columns.RETRY_COUNT","5984","Specify the precision","Decision","DBMIG_APP"',
        '"table","Schemas.DBMIG_APP.Tables.LOAN.Columns.LEGACY_SCORE","5984","Specify the precision","Decision","DBMIG_APP"',
    ]) + "\n"
    mi = parse.parse_csv_text(mixed_csv)["issues"][0]
    check("SCT's own total is preserved", mi["occurrences"], 3)
    check("only the real object is actionable", mi["actionable_occurrences"], 1)
    check("the internals are counted, not dropped", mi["internal_occurrences"], 2)
    check("the actionable object is named", mi["object_name"], "LOAN.LEGACY_SCORE")
    check("internals are held apart", sorted(mi["internal_objects"]),
          ["AQ$_Q_H.RETRY_COUNT", "DR$IX_NOTES$B.STATUS"])
    check("a mixed item is not all-internal", mi["all_internal"], False)

    only_internal_csv = "\n".join([
        '"Category","Occurrence","Action item","Group","Estimated complexity","Schema name"',
        '"table","Schemas.DBMIG_APP.Tables.DR$IX_NOTES$I","5659","DMS SC cannot convert tables without a primary key","Simple","DBMIG_APP"',
    ]) + "\n"
    # **The one that matters for a plan.** An item whose every occurrence is
    # an Oracle-generated object is not work, and must not be shown as any.
    oi = parse.parse_csv_text(only_internal_csv)["issues"][0]
    check("an all-internal item is flagged", oi["all_internal"], True)
    check("...with nothing actionable", oi["actionable_occurrences"], 0)
    truthy("...and says so in the object name",
           "Oracle internal" in oi["object_name"])

    # The object comes from the leaf of SCT's tree path -- there is no
    # object-name column at all.
    q = by_code["9994"]
    check("object name from the tree path leaf", q["object_name"], "LOAN_EVENT_QTAB")
    check("object type from the segment before it", q["object_type"], "Tables")
    check("schema read", q["owner"], "DBMIG_APP")

    # A type whose path segment contains a space must still split correctly.
    dl = by_code["5639"]
    check("dotted path with a spaced segment", dl["object_name"], "DBMIG_LOOPBACK_LNK")
    check("...and its type", dl["object_type"], "Database Links")

    # `Category` is a slug, tidied for display -- not the label to show raw.
    check("category slug tidied", q["category"], "queuing table")

    sev = [i["severity"] for i in r["issues"]]
    check("worst first", sev, ["CRITICAL", "HIGH", "LOW"])
    truthy("severity marked as derived", all(i["severity_is_derived"] for i in r["issues"]))
    ann = route.annotate([{"issue_code": "5984", "occurrences": 1}])[0]
    truthy("annotate carries the method", len(ann.get("how") or []) >= 1)
    truthy("annotate carries the verification", len(ann.get("verify") or []) >= 1)

    truthy("SCT complexity kept verbatim",
           all(i["complexity"] in parse.COMPLEXITY_ORDER for i in r["issues"]))
    truthy("every issue says it came from SCT",
           all(i["source"] == "aws-sct" for i in r["issues"]))
    truthy("SCT's recommendation carried", by_code["5639"]["recommendation"])
    truthy("complexity meaning carried",
           r["complexity_meaning"]["decision"].startswith("not a code"))

    check("BOM tolerated", parse.parse_csv_text("\ufeff" + SAMPLE_CSV)["action_item_count"], 3)
    check("blank rows skipped",
          parse.parse_csv_text("Category,Action item\n,\n")["action_item_count"], 0)
    check("empty csv survives", parse.parse_csv_text("")["action_item_count"], 0)

    # An older or future SCT shape must still parse rather than yield nothing.
    alt = ("Code,Count,Complexity,Category,Description,Recommended action,"
           "Object name,Object type,Schema\n"
           "1,5,Medium,Views,x,y,V1,VIEW,S1\n")
    a = parse.parse_csv_text(alt)
    check("an alternative header still parses", a["action_item_count"], 1)
    check("its own count is honoured", a["issues"][0]["occurrences"], 5)
    check("its object name is used", a["issues"][0]["object_name"], "V1")

    # A column nobody has seen before is reported, not dropped.
    future = SAMPLE_CSV.replace('"Schema name"', '"Schema name","Brand New Column"', 1)
    future = "\n".join(
        ln + ',"x"' if i and ln else ln
        for i, ln in enumerate(future.split("\n"))
    )
    check("an unknown column is reported",
          parse.parse_csv_text(future)["unmapped_columns"], ["Brand New Column"])


def test_toolchain_and_plan():
    print("toolchain and plan")
    tc = toolchain.discover()
    names = [c["name"] for c in tc.as_dict()["checks"]]
    check("three prerequisites checked", names,
          ["java_runtime", "sct_installed", "oracle_jdbc_driver"])
    for c in tc.as_dict()["checks"]:
        if c["status"] != "ok":
            truthy(f"{c['name']} says how to fix it", c["remedy"])

    p = runner.plan(target_id="rds-postgresql", dsn="localhost:1521/XEPDB1",
                    user="u", schemas=["DBMIG_APP"], collector_run_id="abc12345")
    check("plan needs no password", "password" in json.dumps(p), False)
    truthy("plan names the target", p["target"]["label"])
    truthy("plan reports readiness", "ready" in p)
    truthy("plan lists the commands", "CreateReport" in p["commands"])

    # A refusal must name the missing prerequisite, not just fail.
    if not tc.ready:
        r = runner.assess(target_id="rds-postgresql", dsn="localhost:1521/XEPDB1",
                          user="u", password="p", schemas=["DBMIG_APP"],
                          collector_run_id="selftest", reuse_cached=False)
        check("refuses without a toolchain", r["ok"], False)
        truthy("refusal names the reason", r["reason"])
        truthy("refusal carries the checks", r["toolchain"]["checks"])
        check("refusal leaks no password", "password" in json.dumps(r), False)


def test_routing():
    print("routing")
    # Every code in the table must carry a complete, valid row. A half-filled
    # row is worse than a missing one: it routes silently on a default.
    for code, row in route.ROUTES.items():
        check(f"{code} has a valid destination", row["where"] in
              (route.SOURCE, route.TARGET, route.DECISION, route.HUMAN), True)
        check(f"{code} has a valid actor", row["who"] in
              (route.AUTO, route.MODEL, route.PERSON), True)
        truthy(f"{code} explains itself", len(row["why"]) > 60)
        truthy(f"{code} says what clears it", len(row["clears_when"]) > 15)
        # **A remediation screen must answer "how do I solve this".** A finding
        # plus a definition of done is not a method, and 5984 shipped with only
        # the latter -- the largest source item on the estate offered no
        # approach at all.
        truthy(f"{code} proposes how to solve it", len(row.get("how") or []) >= 1)
        # And what a person must confirm before it is applied. The guarantee
        # existed in code (nothing is ever auto-applied) but was invisible on
        # screen, which makes it unverifiable by the person relying on it.
        truthy(f"{code} says what a human must verify",
               len(row.get("verify") or []) >= 1)
        for step in row.get("how") or []:
            truthy(f"{code} how-step is a real instruction", len(step) > 25)

    # **An unmapped code must route to a person, never to automatic.** This is
    # the whole reason the table exists, and the one assertion that cannot be
    # allowed to regress.
    u = route.route("99999")
    check("an unmapped code is not automatic", u["who"] == route.AUTO, False)
    check("an unmapped code goes to a person", u["who"], route.PERSON)
    check("an unmapped code is flagged as unmapped", u["mapped"], False)
    truthy("an unmapped code says why it is unmapped", "not in DBShift" in u["why"])
    truthy("an unmapped code still says how to proceed", len(u.get("how") or []) >= 1)
    truthy("...and what to verify", len(u.get("verify") or []) >= 1)
    check("a mapped code is flagged mapped", route.route("5639")["mapped"], True)

    # Nothing may be auto-applied to the source. An automatic statement against
    # a client's production Oracle is not a thing this project does.
    for code, row in route.ROUTES.items():
        if row["where"] == route.SOURCE:
            check(f"{code} is not auto-applied to the source",
                  row["who"] == route.AUTO, False)

    # Only a target-side item may be automatic at all.
    for code, row in route.ROUTES.items():
        if row["who"] == route.AUTO:
            check(f"{code} is automatic only because it is target-side",
                  row["where"], route.TARGET)

    # A DECISION has no statement by definition, so it cannot be model-drafted.
    for code, row in route.ROUTES.items():
        if row["where"] == route.DECISION:
            check(f"{code} is a decision, so no statement is drafted",
                  row["who"], route.PERSON)

    # Segregation over the real 14 codes.
    issues = [{"issue_code": c, "occurrences": 1} for c in route.ROUTES]
    seg = route.segregate(issues)
    check("four groups, always", len(seg["groups"]), 4)
    check("group order is source, target, decision, human",
          [g["where"] for g in seg["groups"]],
          [route.SOURCE, route.TARGET, route.DECISION, route.HUMAN])
    check("every item lands in exactly one group",
          sum(g["item_count"] for g in seg["groups"]), len(route.ROUTES))
    check("totals add up", seg["totals"]["automatable"] +
          seg["totals"]["ai_draftable"] + seg["totals"]["human_only"],
          len(route.ROUTES))
    check("nothing shipped is unmapped", seg["unmapped"], [])
    truthy("each group explains what it means",
           all(len(g["meaning"]) > 40 for g in seg["groups"]))

    # An unmapped item is surfaced in the segregation, not hidden.
    seg2 = route.segregate([{"issue_code": "99999", "occurrences": 3}])
    check("an unmapped item is reported", len(seg2["unmapped"]), 1)

    # Blocking, and the migration-mode rule Phase 2 already applies: on a
    # full-load run a CDC-only blocker blocks nothing.
    full_load = ["provision", "migrate_full_load", "validate", "cutover"]
    codes_cdc = {b["issue_code"] for b in route.blocking(issues)}
    codes_fl = {b["issue_code"] for b in route.blocking(issues, full_load)}
    truthy("5200 external tables blocks the full load", "5200" in codes_fl)
    truthy("5659 no primary key blocks CDC", "5659" in codes_cdc)
    check("5659 does not block a full-load run", "5659" in codes_fl, False)
    truthy("fewer blockers on a full load than with CDC", len(codes_fl) < len(codes_cdc))

    # The phase names must be the gate's own, or a blocker names a phase that
    # does not exist and is silently never matched.
    from blocker import policy as bpolicy
    for code, row in route.ROUTES.items():
        for phase in row["blocks"]:
            check(f"{code} blocks a real downstream phase",
                  phase in bpolicy.DOWNSTREAM, True)

    # The routing is deterministic: the model must never influence it.
    src = (Path(__file__).resolve().parent / "route.py").read_text(encoding="utf-8")
    check("routing imports no model client", "bedrock" in src.lower(), False)
    truthy("routing says the model never decides it", "never decides" in src)


def test_download_filenames():
    print("download filenames")
    from . import export as E

    # **The bug this guards.** SCT names its CSV after the virtual target, so the
    # real filename carries a space and parentheses straight from the vendor.
    # Edge rejects that inside a quoted Content-Disposition filename and falls
    # back to a GUID with **no extension**, which then will not open -- reported
    # from a real TELCO run on 2026-09-17. `report/export.py` has always
    # sanitised; this path passed SCT's names through raw.
    real = "PostgreSQL_3cPostgreSQL (virtual)3e.csv"
    got = E.safe_filename(real)
    check("space removed from SCT's own filename", " " in got, False)
    check("parentheses removed", ("(" in got) or (")" in got), False)
    check("extension kept", got.endswith(".csv"), True)
    truthy("the name is still recognisable", "PostgreSQL" in got)

    # Every character a Content-Disposition parse can trip on.
    for ch in ' ()<>@,;:\\"/[]?={}	':
        out = E.safe_filename(f"a{ch}b.pdf")
        check(f"{ch!r} stripped", ch in out, False)

    # A name of nothing but unsafe characters must not become a bare ".pdf".
    check("all-unsafe name falls back", E.safe_filename("((( ))).pdf"),
          "aws-sct-report.pdf")
    check("empty name falls back", E.safe_filename(""), "aws-sct-report")

    # An already-clean name must survive untouched -- sanitising must not
    # mangle the common case.
    clean = "dbshift-DBMIG_TELCO-rds-postgresql.pdf"
    check("a clean name is unchanged", E.safe_filename(clean), clean)

    # Windows caps a path component at 255 characters.
    truthy("an absurd name is truncated", len(E.safe_filename("x" * 400 + ".pdf")) <= 184)

    # The server must use it. Asserted against the source so a refactor that
    # drops the call is caught here rather than by a client's browser.
    server = (Path(__file__).resolve().parent.parent / "web" / "server.py").read_text(
        encoding="utf-8")
    # Three call sites (pdf, xlsx, csv). The count is 4 because the helper's own
    # `def` line matches the same substring, so compare on calls only.
    check("every download route uses the shared helper",
          server.count("headers={\"Content-Disposition\": _sct_disposition("), 3)
    check("no route builds a disposition by hand",
          'filename="aws-sct-{target_id}' in server, False)
    truthy("...and that helper sanitises", "safe_filename" in server)


def test_provenance_direction():
    print("provenance")
    # report/export.py exists to say "not AWS SCT". This path is the opposite
    # claim, and the two must never be confused for one another.
    from report import export as rexport
    truthy("report/export.py still disclaims SCT",
           "not generated by AWS SCT" in rexport.PROVENANCE)
    src = (Path(__file__).resolve().parent / "runner.py").read_text(encoding="utf-8")
    check("the SCT path does not import that disclaimer",
          "PROVENANCE" in src, False)
    truthy("artefacts are served verbatim, not re-rendered",
           "verbatim" in src)


def test_internal_prefixes_in_step():
    print("internal prefixes")
    # parse.py declares it keeps these in step with assess/loader.py by hand.
    # Nothing enforced that, and drift is exactly the discrepancy the comment
    # warns about: a finding the rules engine hides and SCT shows, which a
    # client then asks about. Assert the promise instead of trusting it.
    from assess import loader
    check("SCT filters the same internals the rules engine does",
          set(parse.INTERNAL_PREFIXES),
          {p.rstrip("%") for p in loader.INTERNAL_PATTERNS})


def main() -> int:
    print("sct selftest -- no SCT, no database, no AWS\n")
    test_targets()
    test_scenario()
    test_parser()
    test_toolchain_and_plan()
    test_download_filenames()
    test_routing()
    test_provenance_direction()
    test_internal_prefixes_in_step()
    total = PASS + FAIL
    print(f"\n{PASS}/{total} passed" + (f", {FAIL} FAILED" if FAIL else ""))
    return 1 if FAIL else 0


if __name__ == "__main__":
    raise SystemExit(main())
